name: Build and Publish Library with Maven

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml@a092c377743341dedbdf219294d3a07f1c741849 # v1.41.6
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: 21
      slack-channel: '#panda-ci'
      slack-bot-name: "GH-Actions CI"
      slack-bot-icon: ':panda_face:'
